/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jogocorrida;

public class App {

    public static void main(String[] args) {
        veiculo fusca = new veiculo((imotor) new motordefusca() {});
        veiculo ferrari = new veiculo((imotor) new motordeferrari() {});
        veiculo lamborghini = new veiculo((imotor) new motordelamborghini() {});
        
        
        System.out.println(fusca.acelerar());
        System.out.println(ferrari.acelerar());
        System.out.println(lamborghini.acelerar());
    }
}
